import { writeFile, mkdir } from "node:fs/promises";
import { codeToHtml } from "shiki";

// Source of truth for the API code snippet shown in the "For Developers"
// section of the landing page. Edit here, then run `pnpm gen:snippet`.
const snippet = `await fetch('https://api.agentcaller.io/v1/call', {
  method: 'POST',
  headers: {
    'Authorization': 'Bearer ac_live_...',
    'X-402-Payment': 'usdc:base:0.12'
  },
  body: JSON.stringify({
    phone: '+14155550199',
    objective: 'Book a table for 2 on Friday at 7pm.',
    extract: {
      time: 'string',
      confirmed: 'boolean'
    }
  })
});`;

const html = await codeToHtml(snippet, {
  lang: "javascript",
  theme: "vitesse-dark",
});

const out = `// Generated by scripts/gen-snippet.mjs — do not edit.
// Run \`pnpm gen:snippet\` to regenerate.
export const apiSnippetHtml = ${JSON.stringify(html)};
`;

await mkdir(new URL("../src/generated/", import.meta.url), { recursive: true });
await writeFile(
  new URL("../src/generated/api-snippet.ts", import.meta.url),
  out,
);

console.log("Wrote src/generated/api-snippet.ts");
